name: Gitlab CE Full Deploy
description: |
  Gitlab CE is a free GitHub alternative
version: 10.0.3-ce
category: Versioning
maintainer: Patrick McClory <patrick@mcclory.io
license: Apache 2.0
projectURL: https://github.com/patrickmcclory/rancher-catalog
